# This file was generated by GoReleaser. DO NOT EDIT.
class Cwlogs < Formula
  desc "Easily query groups, streams and events from Amazon Cloudwatch Logs."
  homepage "https://github.com/jason-riddle/cwlogs"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jason-riddle/cwlogs/releases/download/v0.0.2/cwlogs_v0.0.2_darwin_amd64.tar.gz"
    sha256 "c07fa7ca9194631ac3683af6d25fd214af078557f15d0f0f81753c19918155dc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jason-riddle/cwlogs/releases/download/v0.0.2/cwlogs_v0.0.2_linux_amd64.tar.gz"
      sha256 "3de47f6db206c86f81ae8ccd41a1371a35ff505165d3d441da822ba38d8cebf2"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jason-riddle/cwlogs/releases/download/v0.0.2/cwlogs_v0.0.2_linux_arm64.tar.gz"
        sha256 "3d237d7f054389408abbf838ef770f523c53b52e0b1f86f72f7778a0b1035ef1"
      else
        url "https://github.com/jason-riddle/cwlogs/releases/download/v0.0.2/cwlogs_v0.0.2_linux_armv6.tar.gz"
        sha256 "364bfab1c51525167f7e2383b00986697769a77a6c7d116d676fac8e1c512791"
      end
    end
  end

  def install
    bin.install "cwlogs"
  end

  test do
    system "#{bin}/cwlogs --version"
  end
end
